### ISSUE TITLE
Error retrieving file data by hash

### ISSUE THREAD

**Issue by qualiabyte** [eris-ltd/hello-world-dapp#7] opened 2015-03-26 18:30 UTC
Hi, I'm testing Eris for the first time and following the Decerver tutorial. Yesterday I was able to create a new Thelonious chain and deploy the Hello World dapp. To test the dapp, I submitted a filename `foo.md` with some test data. This worked and I'm able to view the file contents from the IPFS web-ui by hash.

However, when I try to retrieve the data by filename in the dapp, I get `Path Resolve error: multihash length inconsistent: &{124  130 [210]}`. Any idea what's wrong here? Thanks in advance!

Here's the log output for the failed request:
```
[martini] Started GET /apis/helloworld/files/foo.md for 127.0.0.1:34418
Stuff
URL /apis/helloworld/files/foo.md
REQUEST: {"URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/apis/helloworld/files/foo.md","RawQuery":"","Fragment":""},"Method":"GET","Host":"localhost:3000","Header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["en-US,en;q=0.5"],"Connection":["keep-alive"],"Referer":["http://localhost:3000/helloworld/"],"User-Agent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0"]},"Body":""}
[Runtime] 2015/03/26 10:53:00 URLOBJ: map[path:[files foo.md] options:map[] error:]
[Runtime] 2015/03/26 10:53:00 Getting the storage for filename:0x0000000000000000000000000000000000000000000000000000666f6f2e6d64
[Runtime] 2015/03/26 10:53:00 Hash: 0x0
response Status: 400 Bad Request
response Headers: map[Date:[Thu, 26 Mar 2015 17:53:00 GMT] Content-Length:[68] Content-Type:[text/plain; charset=utf-8]]
response Body: Path Resolve error: multihash length inconsistent: &{124  130 [210]}
[Runtime] 2015/03/26 10:53:00 File data: Path Resolve error: multihash length inconsistent: &{124  130 [210]}
[Runtime] 2015/03/26 10:53:00 Json string of resp obj:
{"Body":"{ \"data\" : \"Path Resolve error: multihash length inconsistent: \u0026{124  130 [210]}\"}","Header":{},"Status":200}
[Webserver] 2015/03/26 10:53:00 Response status message: 200
[Webserver] 2015/03/26 10:53:00 Response header stuff: map[]
[martini] Completed 200 OK in 1.896473ms
```
And this is the log when I submitted the file:
```
[martini] Started POST /apis/helloworld/files for 127.0.0.1:59956
Stuff
URL /apis/helloworld/files
REQUEST: {"URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/apis/helloworld/files","RawQuery":"","Fragment":""},"Method":"POST","Host":"localhost:3000","Header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["en-US,en;q=0.5"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Content-Length":["81"],"Content-Type":["text/plain; charset=UTF-8"],"Pragma":["no-cache"],"Referer":["http://localhost:3000/helloworld/"],"User-Agent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0"]},"Body":"{\"name\":\"foo.md\",\"data\":\"This%20is%20the%20high%20quality%20data%20in%20foo.md!\"}"}
[Runtime] 2015/03/25 18:45:21 URLOBJ: map[error: path:[files] options:map[]]
[Runtime] 2015/03/25 18:45:21 Working
[Runtime] 2015/03/25 18:45:21 BODYOBJ: map[data:This%20is%20the%20high%20quality%20data%20in%20foo.md! name:foo.md]
POSTing
response Status: 201 Created
response Headers: map[Ipfs-Hash:[Qma5HCJgMfrKq1xeS5gcaVySSy589G7QNWDJguBgQ2BRrR] Location:[/ipfs/Qma5HCJgMfrKq1xeS5gcaVySSy589G7QNWDJguBgQ2BRrR] Date:[Thu, 26 Mar 2015 01:45:21 GMT] Content-Length:[0] Content-Type:[text/plain; charset=utf-8]]
response Body: 
HASH: Qma5HCJgMfrKq1xeS5gcaVySSy589G7QNWDJguBgQ2BRrR
[Runtime] 2015/03/25 18:45:21 Pushing stuff to monk. TxData: [0x0000000000000000000000000000000000000000000000000000666f6f2e6d64 0xae5c348a65d04816a3a0c2c7b5b429906db4823b3dfa450330e1ed9db56bc552]
[Runtime] 2015/03/25 18:45:21 Root contract: 0xcfaa4c649dc45196e21e5a91d673b7538bd72980
[Runtime] 2015/03/25 18:45:21 
2015/03/25 18:45:21 [TXP] (t) 7f76dcce => cfaa4c64 (0) 5a10ac12b958f058ec1f72947eae214a49714dae0b9ff8035f1572c47e42bfeb
2015/03/25 18:45:21 [MONK] Start mining
2015/03/25 18:45:24 [REACTOR] added new subscription to newBlock
2015/03/25 18:45:24 [REACTOR] added new subscription to newTx:pre
2015/03/25 18:45:24 [REACTOR] added new subscription to chainReady
2015/03/25 18:45:24 [REACTOR] added new subscription to newBlock
2015/03/25 18:45:24 [REACTOR] added new subscription to newTx:pre
2015/03/25 18:45:24 [MINER] Started
2015/03/25 18:45:24 [STATE] (~) 5a10ac12b958f058ec1f72947eae214a49714dae0b9ff8035f1572c47e42bfeb
2015/03/25 18:45:24 [STATE] 7f76dcced61f321b4b7b41d329f8e4e8f22eb814: #1 1500000000000000000 (+ 0)
2015/03/25 18:45:24 [STATE] 7f76dcced61f321b4b7b41d329f8e4e8f22eb814: #1 1500000000000000000 (- 0)
2015/03/25 18:45:24 [STATE] (+) cfaa4c649dc45196e21e5a91d673b7538bd72980
2015/03/25 18:45:24 [STATE] 7f76dcced61f321b4b7b41d329f8e4e8f22eb814: #2 1500000000000000000 (- 0)
2015/03/25 18:45:24 [STATE] cfaa4c649dc45196e21e5a91d673b7538bd72980: #0 0 (+ 0)
2015/03/25 18:45:24 [STATE] 7f76dcced61f321b4b7b41d329f8e4e8f22eb814: #2 1500000000000000000 (+ 0)
2015/03/25 18:45:24 [STATE] 7f76dcced61f321b4b7b41d329f8e4e8f22eb814: #2 3000000000000000000 (+ 1500000000000000000)
2015/03/25 18:45:24 [MINER] Mining on block 2. Includes 1 transactions
2015/03/25 18:45:25 [POW] Hashing @7khash
2015/03/25 18:45:26 [STATE] (~) 5a10ac12b958f058ec1f72947eae214a49714dae0b9ff8035f1572c47e42bfeb
2015/03/25 18:45:26 [STATE] 7f76dcced61f321b4b7b41d329f8e4e8f22eb814: #1 1500000000000000000 (+ 0)
2015/03/25 18:45:26 [STATE] 7f76dcced61f321b4b7b41d329f8e4e8f22eb814: #1 1500000000000000000 (- 0)
2015/03/25 18:45:26 [STATE] (+) cfaa4c649dc45196e21e5a91d673b7538bd72980
2015/03/25 18:45:26 [STATE] 7f76dcced61f321b4b7b41d329f8e4e8f22eb814: #2 1500000000000000000 (- 0)
2015/03/25 18:45:26 [STATE] cfaa4c649dc45196e21e5a91d673b7538bd72980: #0 0 (+ 0)
2015/03/25 18:45:26 [STATE] 7f76dcced61f321b4b7b41d329f8e4e8f22eb814: #2 1500000000000000000 (+ 0)
2015/03/25 18:45:26 [STATE] 7f76dcced61f321b4b7b41d329f8e4e8f22eb814: #2 3000000000000000000 (+ 1500000000000000000)
2015/03/25 18:45:26 [STATE] Processed block #2 (b3ef9189...)
2015/03/25 18:45:26 [CHAIN] Block #2 passed (b3ef9189...)
2015/03/25 18:45:26 [CHAIN] Imported 1 blocks. #2 (b3ef9189) / 2 (b3ef9189)
2015/03/25 18:45:26 [MINER] posting new block!
2015/03/25 18:45:26 [MINER] 🔨  Mined block b3ef918903653ee8787f6b436f14ce20e586a21ceba92856d10c313ae36eed1b
2015/03/25 18:45:26 [MINER] 
	BLOCK(b3ef918903653ee8787f6b436f14ce20e586a21ceba92856d10c313ae36eed1b): Size: 507.00 B
	PrevHash:   89fa8c92513b2554cdae59d668ae4d7cf9e8516c71de4e5897c3b304afca834c
	UncleSha:   1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
	Coinbase:   7f76dcced61f321b4b7b41d329f8e4e8f22eb814
	Root:       8c279dadc57e7e619bd7f40b5a30b5682df9073181234f2ced5b308884fef1ba
	TxSha:      d3c4556ba8d9cf8b50cb204cad9aa8be027cdbf289c4d32ce75f30608d374ec5
	Difficulty: 32768
	Number:     2
	MinGas:     10000000000000
	MaxLimit:   100000000000000000000000000000000000000000000000000
	GasUsed:    0
	Time:       1427334324
	Extra:      
	Nonce:      b49151a4bbe14d6ebdc83a45c74058b357bb744919ab487babb4bbe1580fa5e5
	NumTx:      1

2015/03/25 18:45:26 [STATE] 7f76dcced61f321b4b7b41d329f8e4e8f22eb814: #2 4500000000000000000 (+ 1500000000000000000)
2015/03/25 18:45:26 [MINER] Mining on block 3. Includes 0 transactions
2015/03/25 18:45:26 [POW] Breaking from mining
2015/03/25 18:45:26 [STATE] 7f76dcced61f321b4b7b41d329f8e4e8f22eb814: #2 4500000000000000000 (+ 1500000000000000000)
2015/03/25 18:45:26 [MINER] Mining on block 3. Includes 0 transactions
2015/03/25 18:45:26 [MINER] Stopping...
2015/03/25 18:45:26 [POW] Breaking from mining
2015/03/25 18:45:26 [MINER] Stopped
[Runtime] 2015/03/25 18:45:26 Json string of resp obj:
{"Body":"Not supported.","Header":{},"Status":200}
[Webserver] 2015/03/25 18:45:26 Response status message: 200
[Webserver] 2015/03/25 18:45:26 Response header stuff: map[]
[martini] Completed 200 OK in 4.85026485s
2015/03/25 18:45:26 [REACTOR] removed subscription to newBlock
2015/03/25 18:45:26 [REACTOR] removed subscription to newTx:pre
2015/03/25 18:45:26 [REACTOR] removed subscription to newBlock
2015/03/25 18:45:26 [REACTOR] removed subscription to newTx:pre
2015/03/25 18:45:26 [MONK] Stopped mining
2015/03/25 18:46:47 [PEER] Connection to peer failed. Giving up.dial tcp 111.111.111.111:9999: i/o timeout
```

**Comment by androlo** [comment] 2015-03-27 03:34
Hi! The issue is it does not store the data properly on the blockchain. This is normally because the chain is not set up (the most common issue thus far). 

The submit log shows a proper IPFS hash (`Qma5HCJgMfrKq1xeS5gcaVySSy589G7QNWDJguBgQ2BRrR`) which means it was added to the  filestore, and on the line below that I see it being converted from base58 to hex and submitted to the chain, except it did not stick. When fetching it, you get `0x0`, which triggers the error `response Body: Path Resolve error: multihash length inconsistent: &{124  130 [210]}` because the hash length needs to be a multiple of 2 (it represent bytes).

The root contract address `0xcfaa4...` suggests that the `package.json` file has not been updated. That is the default value. You should make sure the EPM stuff is done right by following those instructions and be sure to copy the chain id and root contract into the package.json file. I'm assuming you're building it from source. If it still does not work please let us know, as there may be something wrong in the instructions then.

Btw. All this is awkward, yes, and we know that, so we're currently migrating to a node.js setup instead where a lot of the EPM stuff will be possible to do from a webpage that automates a lot of that stuff.

**Comment by compleatang** [comment] 2015-03-27 13:33
I think this is right. The fact that there are no [VM] log lines probably means that it isn't connected into the `root_contract` correctly. The logs should look something like this before the block is mined:

```
2015/03/25 10:27:28 [MONK] Start mining
2015/03/25 10:27:31 [REACTOR] added new subscription to newBlock
2015/03/25 10:27:31 [REACTOR] added new subscription to newTx:pre
2015/03/25 10:27:31 [REACTOR] added new subscription to chainReady
2015/03/25 10:27:31 [REACTOR] added new subscription to newBlock
2015/03/25 10:27:31 [REACTOR] added new subscription to newTx:pre
2015/03/25 10:27:31 [MINER] Started
2015/03/25 10:27:31 [STATE] (+) dacf4c2cb2fe9f40e1451f7471e0919c154426ad
2015/03/25 10:27:31 [STATE] (~) 5f37250603b38c2877f2e5388f5fb927fcfb971c7100d5591c75c2d8aff536f3
2015/03/25 10:27:31 [STATE] dacf4c2cb2fe9f40e1451f7471e0919c154426ad: #0 0 (+ 0)
2015/03/25 10:27:31 [MINER] Stopping...
2015/03/25 10:27:31 [STATE] dacf4c2cb2fe9f40e1451f7471e0919c154426ad: #0 0 (- 0)
2015/03/25 10:27:31 [STATE] dacf4c2cb2fe9f40e1451f7471e0919c154426ad: #1 0 (- 0)
2015/03/25 10:27:31 [STATE] f59ff01425765c7758503608355ca29b5c60642d: #0 0 (+ 0)
2015/03/25 10:27:31 [VM] (code) f59ff01425765c7758503608355ca29b5c60642d gas: 199999999999180 (d) 0000000000000000000000000000000000000000000000006772656574696e6775d6d78062bc88f1268989ac0fbb73c3c4811a660d500c423182ede9a962d1c0
2015/03/25 10:27:31 [VM] (pc) 0   -o- PUSH1          (g) 1   (199999999999179) => 0x00
2015/03/25 10:27:31 [VM] (pc) 2   -o- CALLDATALOAD   (g) 1   (199999999999178) => 0x0000000000000000000000000000000000000000000000006772656574696e67
2015/03/25 10:27:31 [VM] (pc) 3   -o- SLOAD          (g) 20  (199999999999158) {0x6772656574696e67 : 0x}
2015/03/25 10:27:31 [VM] (pc) 4   -o- PUSH1          (g) 1   (199999999999157) => 0x1b
2015/03/25 10:27:31 [VM] (pc) 6   -o- JUMPI          (g) 1   (199999999999156) (f)
2015/03/25 10:27:31 [VM] (pc) 7   -o- PUSH1          (g) 1   (199999999999155) => 0x20
2015/03/25 10:27:31 [VM] (pc) 9   -o- CALLDATALOAD   (g) 1   (199999999999154) => 0x75d6d78062bc88f1268989ac0fbb73c3c4811a660d500c423182ede9a962d1c0
2015/03/25 10:27:31 [VM] (pc) 10  -o- PUSH1          (g) 1   (199999999999153) => 0x00
2015/03/25 10:27:31 [VM] (pc) 12  -o- CALLDATALOAD   (g) 1   (199999999999152) => 0x0000000000000000000000000000000000000000000000006772656574696e67
2015/03/25 10:27:31 [VM] (pc) 13  -o- SSTORE         (g) 200 (199999999998952) {0x6772656574696e67 : 0x75d6d78062bc88f1268989ac0fbb73c3c4811a660d500c423182ede9a962d1c0}
2015/03/25 10:27:31 [VM] (pc) 14  -o- PUSH1          (g) 1   (199999999998951) => 0x01
2015/03/25 10:27:31 [VM] (pc) 16  -o- PUSH1          (g) 1   (199999999998950) => 0x00
2015/03/25 10:27:31 [VM] (pc) 18  -o- MSTORE         (g) 2   (199999999998948) => 0x1
2015/03/25 10:27:31 [VM] (pc) 19  -o- PUSH1          (g) 1   (199999999998947) => 0x20
2015/03/25 10:27:31 [VM] (pc) 21  -o- PUSH1          (g) 1   (199999999998946) => 0x00
2015/03/25 10:27:31 [VM] (pc) 23  -o- RETURN         (g) 1   (199999999998945) => (32) 0x0000000000000000000000000000000000000000000000000000000000000001
2015/03/25 10:27:31 [STATE] dacf4c2cb2fe9f40e1451f7471e0919c154426ad: #1 0 (+ 0)
2015/03/25 10:27:31 [STATE] dacf4c2cb2fe9f40e1451f7471e0919c154426ad: #1 1500000000000000000 (+ 1500000000000000000)
2015/03/25 10:27:31 [MINER] Mining on block 3. Includes 1 transactions
2015/03/25 10:27:32 [POW] Hashing @5khash
...
2015/03/25 10:27:44 [POW] Hashing @5khash
2015/03/25 10:27:44 [STATE] (+) dacf4c2cb2fe9f40e1451f7471e0919c154426ad
2015/03/25 10:27:44 [STATE] (~) 5f37250603b38c2877f2e5388f5fb927fcfb971c7100d5591c75c2d8aff536f3
2015/03/25 10:27:44 [STATE] dacf4c2cb2fe9f40e1451f7471e0919c154426ad: #0 0 (+ 0)
2015/03/25 10:27:44 [STATE] dacf4c2cb2fe9f40e1451f7471e0919c154426ad: #0 0 (- 0)
2015/03/25 10:27:44 [STATE] dacf4c2cb2fe9f40e1451f7471e0919c154426ad: #1 0 (- 0)
2015/03/25 10:27:44 [STATE] f59ff01425765c7758503608355ca29b5c60642d: #0 0 (+ 0)
2015/03/25 10:27:44 [VM] (code) f59ff01425765c7758503608355ca29b5c60642d gas: 199999999999180 (d) 0000000000000000000000000000000000000000000000006772656574696e6775d6d78062bc88f1268989ac0fbb73c3c4811a660d500c423182ede9a962d1c0
2015/03/25 10:27:44 [VM] (pc) 0   -o- PUSH1          (g) 1   (199999999999179) => 0x00
2015/03/25 10:27:44 [VM] (pc) 2   -o- CALLDATALOAD   (g) 1   (199999999999178) => 0x0000000000000000000000000000000000000000000000006772656574696e67
2015/03/25 10:27:44 [VM] (pc) 3   -o- SLOAD          (g) 20  (199999999999158) {0x6772656574696e67 : 0x}
2015/03/25 10:27:44 [VM] (pc) 4   -o- PUSH1          (g) 1   (199999999999157) => 0x1b
2015/03/25 10:27:44 [VM] (pc) 6   -o- JUMPI          (g) 1   (199999999999156) (f)
2015/03/25 10:27:44 [VM] (pc) 7   -o- PUSH1          (g) 1   (199999999999155) => 0x20
2015/03/25 10:27:44 [VM] (pc) 9   -o- CALLDATALOAD   (g) 1   (199999999999154) => 0x75d6d78062bc88f1268989ac0fbb73c3c4811a660d500c423182ede9a962d1c0
2015/03/25 10:27:44 [VM] (pc) 10  -o- PUSH1          (g) 1   (199999999999153) => 0x00
2015/03/25 10:27:44 [VM] (pc) 12  -o- CALLDATALOAD   (g) 1   (199999999999152) => 0x0000000000000000000000000000000000000000000000006772656574696e67
2015/03/25 10:27:44 [VM] (pc) 13  -o- SSTORE         (g) 200 (199999999998952) {0x6772656574696e67 : 0x75d6d78062bc88f1268989ac0fbb73c3c4811a660d500c423182ede9a962d1c0}
2015/03/25 10:27:44 [VM] (pc) 14  -o- PUSH1          (g) 1   (199999999998951) => 0x01
2015/03/25 10:27:44 [VM] (pc) 16  -o- PUSH1          (g) 1   (199999999998950) => 0x00
2015/03/25 10:27:44 [VM] (pc) 18  -o- MSTORE         (g) 2   (199999999998948) => 0x1
2015/03/25 10:27:44 [VM] (pc) 19  -o- PUSH1          (g) 1   (199999999998947) => 0x20
2015/03/25 10:27:44 [VM] (pc) 21  -o- PUSH1          (g) 1   (199999999998946) => 0x00
2015/03/25 10:27:44 [VM] (pc) 23  -o- RETURN         (g) 1   (199999999998945) => (32) 0x0000000000000000000000000000000000000000000000000000000000000001
2015/03/25 10:27:44 [STATE] dacf4c2cb2fe9f40e1451f7471e0919c154426ad: #1 0 (+ 0)
2015/03/25 10:27:44 [STATE] dacf4c2cb2fe9f40e1451f7471e0919c154426ad: #1 1500000000000000000 (+ 1500000000000000000)
2015/03/25 10:27:44 [STATE] Processed block #3 (a821e6bf...)
2015/03/25 10:27:44 [CHAIN] Block #3 passed (a821e6bf...)
2015/03/25 10:27:44 [CHAIN] Imported 1 blocks. #3 (a821e6bf) / 3 (a821e6bf)
2015/03/25 10:27:44 [MINER] posting new block!
2015/03/25 10:27:44 [REACTOR] subscribing channel 0 to event newBlock blocked. skipping
2015/03/25 10:27:44 [REACTOR] subscribing channel 2 to event newBlock blocked. skipping
2015/03/25 10:27:44 [REACTOR] subscribing channel 3 to event newBlock blocked. skipping
2015/03/25 10:27:44 [MINER] 🔨  Mined block a821e6bf3c7277579dfa54e74a698cb70bd0a831e2df8635fd75b3518ef1ea0e
```

One thing to check is if your decerver and epm are on current masters. If this is the first time you've played with Eris then it shouldn't be a problem. If you've played in the past then you may need to pull in the current master. 

Hope there's an easy fix here.

**Comment by qualiabyte** [comment] 2015-03-28 03:48
Ah, changing the root_contract id in package.json fixed the issue. Thought I had done this already, but it was still set to the `0xcfaa4...` address. Now I'm able to submit the file and retrieve it by name. Also I see the VM logs as the contract is running correctly.

That's great, because everything else in the Decerver tutorial went smoothly. I really appreciate how your tools seem to generally match the developer mindset, ever since working with the ruby version of @compleatang's EPM last year. Also recently enjoyed some of @androlo's Smart Systems of Smart Contracts, since Solidity seems like a really important step for contract development.

My only critical feedback is that the tutorials for Decerver and Thelonious can feel a little overwhelming due to their length and detail. On the other hand, you've already made it relatively easy to deploy a custom chain. That's very cool, so thanks for paving the way!

**Comment by androlo** [comment] 2015-03-28 03:50
yeah all the epm stuff will be in a webbrowser. hoping that i can be like a wizard where you can add some basic settings with an option to go in and edit the configuration files directly before it deploys. it'd have tooltips and stuff like that to help during the process. that would be real nice.

**Comment by androlo** [comment] 2015-03-28 03:53
along with a general chain browser/manager

**Comment by compleatang** [comment] 2015-03-28 14:00
Thanks for the feedback. We're about to ship some major simplifications to the tutorials this week upcoming which we think will make on boarding quite a bit easier. It is true that the guides were a bit complex, and they were our first run at how to explain this in the easiest possible way. Now that we have better feedback loops in place we'll be iterating the tutorials a bit more frequently. 

@qualiabyte am going to close this issue since it seems it has been fixed, but feel free to reopen if that assumption is not correct.

**Closed by compleatang** 2015-03-28 14:00 UTC
